### ISSUE TITLE
Developer Consople CPU consumption

### ISSUE THREAD

**Issue by alexcastillo** [neurosity/notion-js#32]
From Matthieu:

"Speaking of the dashboard, it seems to use quite a bit of CPU (40-50% on my machine). Not a big deal, especially at this stage, but Chrome already killed the page a couple times due to freezes."

https://support.neurosity.co/hc/en-us/community/posts/360055931631-First-thoughts-on-Notion-DK1

**Comment by matthieu** [comment]
Here is a screenshot showing the CPU activity reported by Chromium, even with no metric recording.
![Screenshot from 2020-01-14 09-55-23](https://user-images.githubusercontent.com/4904/72369364-c9732080-36b4-11ea-8dcd-b2505d23e745.png)

**Comment by pwstegman** [comment]
High CPU was coming from the metric timeline. I've changed the chart to update once a second (in sync with the data from the device, which is streamed once a second), and this reduced CPU usage quite a bit. Less than 10% on my machine where it was previously over 25%.
