### ISSUE TITLE
BUG: Re-subscribe when internet connection is lost and regained in notion-js 

### ISSUE THREAD

**Issue by andrewjaykeller** [neurosity/notion-js#33]
# Expected

A client should be able to put their process to sleep and wake it up _t_ time later, generally greater than 3 minutes, and be able to immediately resume getting metrics.

#  Problem

A new subscription is created when Notion is instantiated with this library. Then if the client is, say a developer console in a chrome tab, cut off from the internet for more than two minutes (e.g. 30 minutes during a commute to work) the subscription is automatically cleaned up by the firebase API. Then when the client reconnects to the internet again the subscription is **not** requested again and no metrics begin to stream into our client. 

# Solution 

Implement a local store in Notion JS to request metrics again on reconnecting to firebase servers.

**Comment by alexcastillo** [comment]
Fixed on #38
