### ISSUE TITLE
Can't find what thoughts have already been trained on the API. 

### ISSUE THREAD

**Issue by mrommel0** [neurosity/notion-js#56]
For Kinesis applications, it will be necessary to query what thoughts have already been trained, so a user can choose which thought to use

**Comment by iampalop** [comment]
Do you know how to get each probability score from multi-kinesis label?
I am trying to use multi-kinesis label at the same time (to make them as choices).

Do you have any suggestions?

**Comment by alexcastillo** [comment]
Hi @iampalop,

Unfortunately, the Kinesis API doesn't support multi-label classification.

**Comment by iampalop** [comment]
Hi @alexcastillo,
Thank you for your replied.
Now, I am using raw predictions with multi-label.
Can I get each probability score from each label at the same time?

**Comment by alexcastillo** [comment]
I'm afraid not. We recommend implementing your own classifier for multi-label support.

**Comment by alexcastillo** [comment]
I'm happy to report you can now access all trained kinesis labels.

```js
const getUniqueLabels = (experiments) => {
  const labels = experiments.flatMap((experiment) => experiment.labels);
  // only return unique labels
  return [...new Set(labels)];
}

notion.onUserExperiments().subscribe((experiments) => {
  console.log(experiments);
  console.log("labels", getUniqueLabels(experiments));
});

// [{ id: '...', deviceId: '...', labels: [ 'drop' ], name: 'Lightgray cheetah', timestamp: 1577908381552, totalTrials: 16, userId: '...' }]
// ["drop", "lift", "push"]
```
