### ISSUE TITLE
Questions on training, recording, fitting

### ISSUE THREAD

**Issue by devidw** [neurosity/notion-js#93]
Trying to implement the training API into a custom frontend to experiment with different training experiences.

I have read over the [docs article](https://docs.neurosity.co/docs/guides/training), but I am still trying to understand how to get things working properly.

Couple of questions on this topic:

- Is there an example of an implementation of a multi-trial training in the form of code available?

## Recording

- Will `notion.training.record()` will automatically take snapshots until `notion.training.stop()` is called, or those this requires to call record multiple times and is more like taking a "photo" and not "recording a video"?

Start/stop like this:

![Screenshot 2022-11-08 at 12 09 06](https://user-images.githubusercontent.com/68775926/200549310-b8c2ab06-a994-46b2-aaee-108a43a79057.png)

Or single shots like this:

![Screenshot 2022-11-08 at 12 09 39](https://user-images.githubusercontent.com/68775926/200549411-b3d9e3d2-7263-41a0-8a20-ff2677a762de.png)

## Fitting

- When doing a training with multiple rounds/trials, should `fit: true` be recorded after each round, after each pair of rest/active, or should it only be called once after all rounds have finished?
- Is there a difference/preferred way between calling `baseline: true, fit: true` or `baseline: false, fit: true`?
- Furthermore, should `fit` be recorded independently of the rest/active recordings, or should it be called along one of these?

## Misc

- The predefined labels available to train in the [console](https://console.neurosity.co/), is there special/optimized analytics behind them when training them or is it the same as when doing training with a custom sting as label from scratch?

**Comment by alexcastillo** [comment]
Hi @devidw,

Thanks for reaching out.

I'll do my best to answer your questions. 

Unfortunately no. 
> Is there an example of an implementation of a multi-trial training in the form of code available?

It's more like taking a snapshot (photo), and there's no need to call stop unless you want to stop it early.
> Will notion.training.record() will automatically take snapshots until notion.training.stop() is called, or those this requires to call record multiple times and is more like taking a "photo" and not "recording a video"?

After each pair.
>When doing a training with multiple rounds/trials, should fit: true be recorded after each round, after each pair of rest/active, or should it only be called once after all rounds have finished?

I recommend you use this combination:
```
const trialDefaults = {
    fit: true,
    baseline: false,
    // ...
};

const baselineDefaults = {
    fit: false,
    baseline: true,
    // ...
};
```

> Is there a difference/preferred way between calling baseline: true, fit: true or baseline: false, fit: true? Furthermore, should fit be recorded independently of the rest/active recordings, or should it be called along one of these?


The latter, no special/optimized analytics behind them.
> The predefined labels available to train in the [console](https://console.neurosity.co/), is there special/optimized analytics behind them when training them or is it the same as when doing training with a custom sting as label from scratch?

I hope this helps. I suggest you check out our [Kinesis FAQ](https://neurosity.notion.site/Kinesis-FAQ-4b105a2ad1a048d6b485fb3fc117a0c1).

**Comment by devidw** [comment]
Thanks a bunch answering all my questions @alexcastillo 

Will close for now and come back when I've got something working, so we can maybe extend the examples/docs when appropriate
